import 'package:flutter/material.dart';
import 'package:greon/presentation/screens/settings_page.dart';
import 'package:table_calendar/table_calendar.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import '../../configs/space.dart';
import '../../core/constant/assets.dart';
import '../../core/router/app_router.dart';
import '../../data/repositories/schedule_repository_impl.dart';
import '../../domain/entities/schedule/schedule.dart';
import '../../domain/usecases/schedule/delete_schedule.dart';

class CalendarScreen extends StatefulWidget {
  final String userId;

  const CalendarScreen({super.key, required this.userId});

  @override
  State<CalendarScreen> createState() => _CalendarScreenState();
}

class _CalendarScreenState extends State<CalendarScreen> {
  DateTime _focusedDay = DateTime.now();
  DateTime? _selectedDay;
  Map<DateTime, List<Schedule>> _events = {};

  @override
  void initState() {
    super.initState();
    _fetchSchedules();
  }

  Future<void> _fetchSchedules() async {
    final firstDayOfMonth = DateTime(_focusedDay.year, _focusedDay.month, 1);
    final lastDayOfMonth = DateTime(_focusedDay.year, _focusedDay.month + 1, 0);

    final snapshot = await FirebaseFirestore.instance
        .collection('users')
        .doc(widget.userId)
        .collection('schedules')
        .where('date',
            isGreaterThanOrEqualTo: Timestamp.fromDate(firstDayOfMonth))
        .where('date', isLessThanOrEqualTo: Timestamp.fromDate(lastDayOfMonth))
        .get();

    final events = <DateTime, List<Schedule>>{};

    for (var doc in snapshot.docs) {
      final data = doc.data();
      final date = (data['date'] as Timestamp).toDate();
      final day = DateTime(date.year, date.month, date.day);

      final schedule = Schedule(
        plantName: data['plant_name'],
        plantId: data['plant_id'],
        date: date,
        type: data['type'],
        memo: data['memo'] ?? '',
        autoGenerated: data['auto_generated'] ?? false,
      );

      events.putIfAbsent(day, () => []).add(schedule);
    }
    // 2️⃣ Firestore에서 식물 목록 가져오기
    final plantsSnapshot = await FirebaseFirestore.instance
        .collection('users')
        .doc(widget.userId)
        .collection('plants')
        .get();

    for (var plantDoc in plantsSnapshot.docs) {
      final plant = plantDoc.data();

      final plantName = plant['name'];
      final plantId = plantDoc.id;

      // ---- 물주기 일정 ----
      if (plant['last_watered_date'] != null &&
          plant['watering_cycle'] != null) {
        final lastWatered = (plant['last_watered_date'] as Timestamp).toDate();
        final cycle = plant['watering_cycle'];
        final nextDate = lastWatered.add(Duration(days: cycle));

        if (nextDate.isAfter(firstDayOfMonth) &&
            nextDate.isBefore(lastDayOfMonth)) {
          final day = DateTime(nextDate.year, nextDate.month, nextDate.day);
          events.putIfAbsent(day, () => []).add(Schedule(
                plantName: plantName,
                plantId: plantId,
                date: nextDate,
                type: '물주기',
                memo: '자동 생성된 물주기 일정',
                autoGenerated: true,
              ));
        }
      }

      // ---- 영양제 일정 ----
      if (plant['last_nutrient_date'] != null &&
          plant['nutrient_frequency'] != null) {
        final lastNutrient =
            (plant['last_nutrient_date'] as Timestamp).toDate();
        final freq = plant['nutrient_frequency'];
        final nextDate = lastNutrient.add(Duration(days: freq));

        if (nextDate.isAfter(firstDayOfMonth) &&
            nextDate.isBefore(lastDayOfMonth)) {
          final day = DateTime(nextDate.year, nextDate.month, nextDate.day);
          events.putIfAbsent(day, () => []).add(Schedule(
                plantName: plantName,
                plantId: plantId,
                date: nextDate,
                type: '영양제',
                memo: '자동 생성된 영양제 일정',
                autoGenerated: true,
              ));
        }
      }

      // ---- 분갈이 일정 ----
      if (plant['last_repotting_date'] != null &&
          plant['repotting_cycle'] != null) {
        final lastRepot = (plant['last_repotting_date'] as Timestamp).toDate();
        final cycle = plant['repotting_cycle'];
        final nextDate = lastRepot.add(Duration(days: cycle));

        if (nextDate.isAfter(firstDayOfMonth) &&
            nextDate.isBefore(lastDayOfMonth)) {
          final day = DateTime(nextDate.year, nextDate.month, nextDate.day);
          events.putIfAbsent(day, () => []).add(Schedule(
                plantName: plantName,
                plantId: plantId,
                date: nextDate,
                type: '분갈이',
                memo: '자동 생성된 분갈이 일정',
                autoGenerated: true,
              ));
        }
      }
    }

    setState(() {
      _events = events;
    });
  }

  List<Schedule> _getEventsForDay(DateTime day) {
    final normalizedDay = DateTime(day.year, day.month, day.day);
    return _events[normalizedDay] ?? [];
  }

  Map<String, List<String>> getGroupedEvents(DateTime day) {
    final events = _getEventsForDay(day);
    final Map<String, List<String>> grouped = {};
    for (var event in events) {
      grouped.putIfAbsent(event.type, () => []).add(event.plantName);
    }
    return grouped;
  }

  String getWeekdayName(DateTime date) {
    const weekdays = ['월', '화', '수', '목', '금', '토', '일'];
    return weekdays[date.weekday - 1];
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: Space.h1!,
      child: SafeArea(
        child: Scaffold(
          body: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Image.asset(AppAssets.greonAppBar, height: 40),
                  IconButton(
                    icon: const Icon(Icons.settings, size: 28),
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (_) => const SettingsPage()),
                      );
                    },
                  ),
                ],
              ),
              SizedBox(
                // SizedBox 높이 강제로 크게 주지 않고, 자연스럽게 크기 잡히게 둬도 됩니다.
                child: TableCalendar<Schedule>(
                  firstDay: DateTime.utc(2020, 1, 1),
                  lastDay: DateTime.utc(2030, 12, 31),
                  focusedDay: _focusedDay,
                  selectedDayPredicate: (day) => isSameDay(_selectedDay, day),
                  eventLoader: _getEventsForDay,
                  rowHeight: 44,
                  // 🔥 기본 52 → 줄여서 달력 높이 감소
                  calendarStyle: CalendarStyle(
                    selectedDecoration: BoxDecoration(
                      color: Colors.green.shade400,
                      shape: BoxShape.circle,
                    ),
                    todayDecoration: const BoxDecoration(
                      color: Colors.lightGreen,
                      shape: BoxShape.circle,
                    ),
                    markerDecoration: const BoxDecoration(
                      color: Colors.deepPurple,
                      shape: BoxShape.circle,
                    ),
                    markersMaxCount: 3,
                  ),
                  headerStyle: const HeaderStyle(
                    formatButtonVisible: false,
                    titleCentered: true,
                    titleTextStyle:
                        TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  calendarBuilders: CalendarBuilders(
                    defaultBuilder: (context, date, _) {
                      final isSunday = date.weekday == DateTime.sunday;
                      final isSaturday = date.weekday == DateTime.saturday;
                      Color? textColor;
                      if (isSunday) {
                        textColor = Colors.red;
                      } else if (isSaturday) {
                        textColor = Colors.blue;
                      }
                      return Center(
                        child: Text(
                          '${date.day}',
                          style: TextStyle(
                            color: textColor,
                            fontWeight: FontWeight.normal,
                          ),
                        ),
                      );
                    },
                    markerBuilder: (context, date, events) {
                      if (events.isEmpty) return null;
                      return Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: events.map((e) {
                          Color color;
                          switch (e.type) {
                            case '물주기':
                              color = Colors.lightBlue;
                              break;
                            case '영양제':
                              color = Colors.yellow;
                              break;
                            case '분갈이':
                              color = Colors.brown;
                              break;
                            default:
                              color = Colors.grey;
                          }
                          return Container(
                            width: 6,
                            height: 6,
                            margin: const EdgeInsets.symmetric(horizontal: 0.5),
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: color,
                            ),
                          );
                        }).toList(),
                      );
                    },
                  ),
                  onDaySelected: (selectedDay, focusedDay) {
                    setState(() {
                      _selectedDay = selectedDay;
                      _focusedDay = focusedDay;
                    });
                  },
                  onPageChanged: (focusedDay) {
                    _focusedDay = focusedDay;
                    _fetchSchedules();
                  },
                ),
              ),
              const SizedBox(height: 8),
              Expanded(
                child: Builder(
                  builder: (context) {
                    final day = _selectedDay ?? _focusedDay;
                    final groupedEvents = getGroupedEvents(day);

                    if (groupedEvents.isEmpty) {
                      return const Center(
                        child: Text('일정이 없습니다.',
                            style: TextStyle(color: Colors.grey)),
                      );
                    }

                    final List<Widget> rows = [];

                    if (groupedEvents['물주기'] != null) {
                      rows.add(Row(
                        children: [
                          const Icon(Icons.water_drop,
                              color: Colors.blue, size: 18),
                          const SizedBox(width: 8),
                          Text(
                            '물 주는 날 - ${groupedEvents['물주기']!.join(", ")}',
                            style: const TextStyle(fontSize: 13),
                          ),
                        ],
                      ));
                    }
                    if (groupedEvents['분갈이'] != null) {
                      rows.add(Row(
                        children: [
                          const Icon(Icons.change_circle,
                              color: Colors.brown, size: 18),
                          const SizedBox(width: 8),
                          Text(
                            '분갈이 하는 날 - ${groupedEvents['분갈이']!.join(", ")}',
                            style: const TextStyle(fontSize: 13),
                          ),
                        ],
                      ));
                    }
                    if (groupedEvents['영양제'] != null) {
                      rows.add(Row(
                        children: [
                          const Icon(Icons.eco, color: Colors.green, size: 18),
                          const SizedBox(width: 8),
                          Text(
                            '영양제 주는 날 - ${groupedEvents['영양제']!.join(", ")}',
                            style: const TextStyle(fontSize: 13),
                          ),
                        ],
                      ));
                    }

                    final weekday = getWeekdayName(day);

                    return Card(
                      color: Colors.grey.shade200,
                      margin: const EdgeInsets.symmetric(
                          vertical: 10, horizontal: 14),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(14)),
                      child: Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              '${day.year}년 ${day.month}월 ${day.day}일 ($weekday)',
                              style: const TextStyle(
                                fontSize: 14,
                                fontWeight: FontWeight.bold,
                                color: Colors.grey,
                              ),
                            ),
                            const SizedBox(height: 10),
                            ...rows.map((w) => Padding(
                                  padding: const EdgeInsets.only(bottom: 8.0),
                                  child: w,
                                )),
                          ],
                        ),
                      ),
                    );
                  },
                ),
              ),
              if (_selectedDay != null)
                Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: ElevatedButton.icon(
                    onPressed: () async {
                      final result = await Navigator.pushNamed(
                        context,
                        AppRouter.addSchedule,
                        arguments: {
                          'userId': widget.userId,
                          'selectedDate': _selectedDay!,
                        },
                      );
                      if (result == true) {
                        _fetchSchedules();
                      }
                    },
                    icon: const Icon(Icons.add),
                    label: const Text('일정 추가'),
                    style: ElevatedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 24, vertical: 8),
                      backgroundColor: Colors.white,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                  ),
                ),
              Padding(
                padding:
                    const EdgeInsets.symmetric(vertical: 8.0, horizontal: 16.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    Column(
                      children: [
                        Container(
                          width: 10,
                          height: 10,
                          decoration: const BoxDecoration(
                            color: Colors.lightBlue,
                            shape: BoxShape.circle,
                          ),
                        ),
                        const SizedBox(height: 4),
                        const Text(
                          '물 주는 날이에요!',
                          style: TextStyle(fontSize: 11),
                          textAlign: TextAlign.center,
                        ),
                      ],
                    ),
                    Column(
                      children: [
                        Container(
                          width: 10,
                          height: 10,
                          decoration: const BoxDecoration(
                            color: Colors.yellow,
                            shape: BoxShape.circle,
                          ),
                        ),
                        const SizedBox(height: 4),
                        const Text(
                          '영양제가 필요해요!',
                          style: TextStyle(fontSize: 11),
                          textAlign: TextAlign.center,
                        ),
                      ],
                    ),
                    Column(
                      children: [
                        Container(
                          width: 10,
                          height: 10,
                          decoration: const BoxDecoration(
                            color: Colors.brown,
                            shape: BoxShape.circle,
                          ),
                        ),
                        const SizedBox(height: 4),
                        const Text(
                          '분갈이 해주세요!',
                          style: TextStyle(fontSize: 11),
                          textAlign: TextAlign.center,
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
