class Schedule {
  final String plantName;
  final String plantId;
  final DateTime date;
  final String type;
  final String memo;
  final bool autoGenerated;

  Schedule({
    required this.plantName,
    required this.plantId,
    required this.date,
    required this.type,
    this.memo = '',
    this.autoGenerated = false,
  });

  Map<String, dynamic> toMap() {
    return {
      'plant_name': plantName,
      'plant_id': plantId,
      'date': date,
      'type': type,
      'memo': memo,
      'auto_generated': autoGenerated,
    };
  }
}
